### ISSUE TITLE
[Feature Request] idToken from an AuthenticationResult is not exposed in the Public API

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#107]
The library exposes function [getAccessToken()](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/msal/authentication_result_provider.go#L9), 
However,  there is not a public api surface to fetch an idToken from a token response. 

Once there we add this api, we can add a check to the e2e tests ro verify if returned object contains an IDtoken.
This was the context in which the need for such an API was found : https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/97#discussion_r537883244

**Comment by element-of-surprise** [comment]
IDToken is now public.
