### ISSUE TITLE
[Feature Request] Support custom http client

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#119]
Refer : https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/117#discussion_r553532502

**Comment by element-of-surprise** [comment]
This should hold until a customer gives a use case we can't support in another way.

**Comment by element-of-surprise** [comment]
If added at some point, should look like:

```go
// HTTP provides an HTTP client that will be used for all HTTP calls. This interface is not covered by any
// compatibility promise. Additions to the stdlib http.Client will be added here and may break compatibility without
// a semantic version change.
type HTTP interface {
    CloseIdleConnections()
    Do(req *Request) (*http.Response, error)
    Get(url string) (*http.Response, error)
    Head(url string) (*http.Response, error)
    Post(url, contentType string, body io.Reader) (*http.Response,error)
    PostForm(url string, data url.Values) (*http.Response,error)
}
```

**Comment by jhendrixMSFT** [comment]
There's no need to add `Get()`, `Head()`, `Post()`, and `PostForm()` as they're convenience methods which aren't applicable to our needs given they don't honor a user-provided context.

I think we can also omit `CloseIdleConnections()`, at least for now until some compelling use-case makes it a requirement (for reference, in the Go SDK we've defined our client interface with just the Do() method and have had no need for this in 4+ years).

**Comment by element-of-surprise** [comment]
A couple things here:

Do we have a current customer for this, if not we should punt this? If that is Joel, you already have code that needs this?
If so, then let's move forward, but if not, we should punt on this.

Joels is right in that we can use just Do() instead of Get(), Head(), Post(), and PostForm().

We cannot do without CloseIdleConnections().

This goes back to the rule: you should never (almost) have a public interface a user can implement.  

Here's why:

HTTP design for today:
```go
type HTTP interface{
  Do(req *Request) (*http.Response, error)
}
```

Our Client's implementation:
```
type HTTP struct {
  client *http.Client
}

func (h *HTTP)  Do(req *http.Request) (*http.Response, error) {
  // Do some custom stuff in here.
  return client.Do(req)
}

HTTP design tomorrow:
```go
type HTTP interface{
  Do(req *Request) (*http.Response, error)
  CloseIdleConnections() // <-added here
}
```

This immediately breaks our clients, as their client is no longer compatible.

So now we have to roll a major version change.  Our language here protects us from when we need to add support because Go team adds a method we require (however, the chance of that is extremely low).  

But if we need to add any method in the future, we are either going to break our clients when we didn't have to (and use language to protect ourselves, which is bad if we can help it) or we are going to roll a major version (let's never do this, its painful for everyone).

**Comment by jhendrixMSFT** [comment]
Yes this is needed by `azidentity` to use our pipeline middleware for providing retries, logging etc.

You are right about adding it later, my bad.  But I'm not yet convinced that this is required in the interface.  When do you envision this being called?

**Comment by element-of-surprise** [comment]
Roger on the need.

I don't envision it being called.  But I don't want to pay for my [lack of vision](https://www.youtube.com/watch?v=BxE1cB5LVew).  That looks like it hurts and I'm allergic to pain.

If we find the need for whatever the reason in the future, we break clients.  As this can't be duplicated with Do(), we need require for the future to protect ourselves.

This is why I don't like user implementable interfaces, you gotta cover all the bases.

**Comment by jhendrixMSFT** [comment]
Being versioning-tolerant has convinced me, will include this in the implementation.

**Comment by jhendrixMSFT** [comment]
Fixed in `dev`
