### ISSUE TITLE
Investigate enforcing confidential client per user in some confidential client scenarios

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#120]
Refer : https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/117#discussion_r553580438 and https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/117#discussion_r553581029

**Comment by bgavrilMS** [comment]
Insufficient context. MSAL should work both when using singleton CCA and when using 1 CCA per request.
