### ISSUE TITLE
CertFromPEM: support PKCS1 and PKCS8, plus pull the leaf cert

### ISSUE THREAD

**Issue by element-of-surprise** [AzureAD/microsoft-authentication-library-for-go#122]
There can definitely be more than one certificate. See Azure/azure-sdk-for-go#5412 for details on the problems as well as our solution.

My problem here is that this func can return multiple certificates however I don't know which one to pass to confidential.NewCredFromCert(). If we have a legitimate use-case for returning all the certs I'm fine with that however we must document which cert is the one to use to authenticate (ideally the first in the slice).

 
@element-of-surprise element-of-surprise 1 hour ago Author Member
So, I don't think that fix is valid, if you are referring to:

  if _, ok := block.Headers["localKeyId"]; ok {
              cert, err = x509.ParseCertificate(block.Bytes)
              if err !=  nil {
                  fmt.Printf("Error parsing certificate from pem block:%v\n", err)
                  continue
              }
            }
I can find no option header standard for PEM that includes "locakKeyId" to tell you that something is the leaf certificate.

When I look at this fix, it seems that the origin is from PKCS12. PKCS12 is a different standard. When a specific library does a PKCS12 to PEM conversion, it pops this in as an optional header.

This looks to be coming from an asn1 id: asn1.ObjectIdentifier([]int{1, 2, 840, 113549, 1, 9, 21}) stored in PKCS12. (source; https://gitlab.cncf.ci/kubernetes/kubernetes/blob/a610ffd71ac8318c1cb2ddc4a234350e61162575/vendor/golang.org/x/crypto/pkcs12/pkcs12.go)

In standard PEM, this is not available unless a conversion was made from this specific pkcs12 package from what I see.

I don't think that fix is a valid fix for this or the library you linked.

So I think your question is actually still open (for both packages), how do you identify the leaf cert in a PEM encoding for all cases. At this point I don't know that answer.

 
@jhendrixMSFT jhendrixMSFT 1 hour ago Member
The fix was to find the certificate with the same public key as that of the provided private key, see https://github.com/Azure/go-autorest/blob/master/autorest/adal/persist.go#L111.

 
@element-of-surprise element-of-surprise 42 minutes ago Author Member
Interesting, though that is with a PKCS1 key instead of a PKCS8 key (which is what I added support for). I'll have to look back, I though the standard for PKCS1 keys was to use RSA PRIVATE KEY and not PRIVATE KEY.

Though, PEM seems to be very loose.

Maybe I really need to add support for PKCS1 and PKCS8 and try to decode both types regardless of what the text is.

I can't imagine how many iterations of features causes certificate/key standards to be such a mess. ASN1.DER/CER, sometimes base64, sometimes not, inside PKCS1, PKCS12, PKCS8, ............

Text headers with options not listed......

 
@element-of-surprise element-of-surprise now Author Member
I'm going to defer this change to the next CL. This will get the big changes out.

The follow-up for this is on my next change.

**Comment by chlowell** [comment]
For reference, here's what we have in the track 2 Azure SDK:
1. Public helper method parses certs and exactly one key from a user's bytes. User gets `[]*x509.Certificate` and `crypto.PrivateKey` ([source](https://github.com/Azure/azure-sdk-for-go/blob/ec0cf6f4d63f4fbc21bc10a971efa96c2a9ec333/sdk/azidentity/client_certificate_credential.go#L111))
2. Internal helper loops over the `[]*x509.Certificate` to identify the signing cert, building x5c content as it goes ([source](https://github.com/Azure/azure-sdk-for-go/blob/ec0cf6f4d63f4fbc21bc10a971efa96c2a9ec333/sdk/azidentity/client_certificate_credential.go#L170))

Our goal with the public helper method is to address common cases that are well supported by the standard library. Users with tricky cases can parse certificates by other means, e.g. another package; our certificate credential constructor takes `[]*x509.Certificate` and `crypto.PrivateKey`.
