### ISSUE TITLE
Investigate XML namespaces handling for parsing of Mex document in ADFS flows

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#124]
XM parsing right now follows a static structure. This structure is based of WS-Trust 13 spec. However ADFS supports a fallback of WStrust 2005 if it does not find WSTrust 13 address and the xml schema for that is a little bit different. 
Reference here : https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/mex.py#L94 
To investigate if changes needed here.

**Comment by bgavrilMS** [comment]
Won't fix.
