### ISSUE TITLE
[Issue] Unclear which branch should be used

### ISSUE THREAD

**Issue by allfro** [AzureAD/microsoft-authentication-library-for-go#142]
### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
The documentation does not specify which branch should be used for production environments. Furthermore, the package repository ([https://pkg.go.dev/search?q=msal](https://pkg.go.dev/search?q=msal)) displays multiple entries to the same project - each with an entirely different API altogether. It would be helpful if the documentation clearly specified the version/branch to use in the `go get` command that is directly associated with the details in the `README.md`.

**Comment by abhidnya13** [comment]
Sorry for the confusion, we have an item #133 to update the `README.md`. Will be able to get to it next week ! Stay tuned.

**Comment by abhidnya13** [comment]
Also, `dev` branch is where the latest code is at.
