### ISSUE TITLE
[Bug] Cannot specify custom API scopes

### ISSUE THREAD

**Issue by allfro** [AzureAD/microsoft-authentication-library-for-go#143]
**Which version of MSAL Go are you using?**
All versions are affected.

**Where is the issue?**
* Public client
    * [x] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [ ] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**
Existing app that is being ported from python to golang

**What version of Go are you using (`go version`)?**

1.14

**What operating system and processor architecture are you using (`go env`)?**

macOS

**Repro**

Using a custom API scope (i.e. `api://<GUID>`) to acquire an access token fails with a declined scope message. 

**Expected behavior**
According to the AzureAD documentation, the authorization and token endpoints cannot be used to request scopes belonging to different audiences within the same request. For example, the App ID represents a unique audience and scopes beginning with `api://<AppID>/<scopeName>` cannot be mixed with `openid`, `profile`, etc.. This behaviour deviates from the behaviour of several of the other MSAL libraries written in different languages and results in an inability to request custom API scopes. Clients should be able to specify custom scopes from the identity provider

**Actual behavior**
We are unable to retrieve tokens with custom API scopes. This is due to the additional scopes (`openid`, `user.read`, `user.read.all`, `email`, `profile`) that are automatically appended to the authorize and token requests. 

**Possible solution**
Remove the automatic addition of default scopes when scopes have explicitly been defined during the initiation requests. Ensure use of the same scopes to retrieve the tokens as well.

**Comment by abhidnya13** [comment]
Hey @allfro,

Can you give more information on what is the error you are getting ? I just tried using a custom api scope and was able to successfully get an accesstoken. So I am not able to repro this. 
The default scopes we add should not interfere with the custom scopes you are requesting. I have added a brief explanation on why here : 

As you quoted :
**According to the AzureAD documentation, the authorization and token endpoints cannot be used to request scopes belonging to different audiences within the same request.**
This is correct. However the example you gave is not entirely correct. The scopes you mentioned. `openid`, `profile` are standard claims in openid. These are added by default in all MSALS and understood by Azure AD. 
The only default scopes we add are:
1. `openid`: This is what it stands for according to [openidconnect spec](https://openid.net/specs/openid-connect-core-1_0.html): OpenID Connect implements authentication as an extension to the OAuth 2.0 authorization process. Use of this extension is requested by Clients by including the `openid` scope value in the Authorization Request. 
2. `offline_access` : This scope value requests that an OAuth 2.0 Refresh Token be issued that can be used to obtain an Access Token that grants access to the End-User's UserInfo Endpoint even when the End-User is not present (not logged in).
3. `profile`: It gives the app access to a large amount of information about the user. The information it can access includes, but isn't limited to, the user's given name, surname, preferred username, and object ID.
Additional scopes like `user.read` or `user.read.all` are not added by MSAL. 

These scopes are standard claims. What the documentation text you quoted means is that The Microsoft identity platform endpoint does not allow you to get a token for several resources at once. Meaning you cannot request scopes like `api://<AppID1>/<scopeName>` and `api://<AppID2>/<scopeName>` in the same request. 

I hope this clarifies the understanding. Let me know if you have more questions.

**Comment by allfro** [comment]
Do you mind sharing a code snippet? Also what branch are you using?

**Comment by abhidnya13** [comment]
You can take a look at the `device_code_flow_sample.go` [here ](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/tests/devapps/device_code_flow_sample.go) for a code snippet. Please use `dev` branch, it has the latest updates.

**Comment by abhidnya13** [comment]
Hey @allfro , do you have any more questions ? Were you able to get through with the sample code ?

**Comment by abhidnya13** [comment]
Closing this. The device code sample from the latest release can be used for this. Feel free to reopen if you have any more questions.
