### ISSUE TITLE
Review all dependencies utilized

### ISSUE THREAD

**Issue by hchittanuru3** [AzureAD/microsoft-authentication-library-for-go#17]

**Comment by bgavrilMS** [comment]
Looks ok to me.

**Comment by chlowell** [comment]
Looks ok to me too (`godebug` and `stats` are test dependencies):
https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/a382af46df305f111976b6f31e82aa88c98d0dc4/go.mod#L6-L10
It's been a while since the last upgrades though: #387

**Comment by chlowell** [comment]
Closing this because we've published v0.9.0 with upgraded dependencies.
