### ISSUE TITLE
Incorrect authority here

### ISSUE THREAD

**Issue by tlkrinke** [AzureAD/microsoft-authentication-library-for-go#185]
https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/90e32ae039776f40b780c12082e1f42a9fc4b6f2/apps/tests/devapps/username_password_sample.go#L15

The config.json file for this sample is not consistent with the config.json described in the readme.  In particular, the authority in the config.json file is:
    "authority": "https://login.microsoftonline.com/common"
and I believe it needs to be:
    "authority": "https://login.microsoftonline.com/organizations"

**Comment by abhidnya13** [comment]
Thanks for bringing this to our notice. I have updated the config file in the PR linked above. 
Besides, we also have a item to improve samples in general so there will be more changes coming through. #172
