### ISSUE TITLE
[Bug] access token is not refreshed after it expires

### ISSUE THREAD

**Issue by jimzshi** [AzureAD/microsoft-authentication-library-for-go#203]
**Which version of MSAL Go are you using?**
Microsoft Authentication Library for Go 1.0.0-preview

**Where is the issue?**
* Confidential client
    * [x] Authorization code flow 

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**What version of Go are you using (`go version`)?**
1.16

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=W:\Go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=W:\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
</pre></details>

**Repro**

<code>var your = (code) => here;</code>

**Expected behavior**
when access token (auth code flow) is expired, AcquireTokenSilent() would renew it using refresh token.

**Actual behavior**
when access token (auth code flow) is expired, AcquireTokenSilent() return error directly.

**Possible solution**
probably we can remove token validation in `func (m *Manager) Read()`
<code>
	if err := accessToken.Validate(); err != nil {
		return TokenResponse{}, err
	}
</code>
?

since AuthResultFromStorage() will check it anyway then try to refresh it if it's invalid.

**Comment by abhidnya13** [comment]
Hi @jimzshi, Thanks for reporting this. I'll be working on a fix. Stay tuned.
