### ISSUE TITLE
[Feature Request] Relax computation of declined scopes

### ISSUE THREAD

**Issue by mzjp2** [AzureAD/microsoft-authentication-library-for-go#214]
**Is your feature request related to a problem? Please describe.**
I was stuck for a couple of hours because I kept getting "declined scopes" from the MSAL library, even though the scopes I requested:

```
Calendars.ReadWrite
User.Read
```

were granted, because the MSAL library looked through the granted scopes, which were `calendars.readwrite`, `user.read` and put the two scopes I defined in the "DeclinedScope" list and failed my request.

After looking through the code and debugging, I found the case, but I think we should either do case-insensitive comparison (the microsoft docs all use the `Calendars.ReadWrite` format) or document what the string format for scopes should be (lowercase), maybe this already exists and I missed it though!

**Comment by abhidnya13** [comment]
Hey @mzjp2, Thanks for bringing this to our attention.
Basically,
openidconnect and oauth scopes are supposed to be case sensitive. 
https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
https://datatracker.ietf.org/doc/html/rfc6749#section-3.3

However, AAD itself treats scopes as case insensitive. So, if you send a scope in a different case, AAD will return it back in a "corrected" case. 

e.g. customer sends `user.read`
MSAL now sends `user.read` to AAD 
AAD returns `User.Read` in response and in access token
 
In your case AAD is indeed granting, `Calendars.ReadWrite`  and `User.Read` but MSAL is converting it to lowercase. I can take a look at solving this next week. Thanks for reporting !
