### ISSUE TITLE
[Bug] Silent refresh fails if custom API scopes are in use

### ISSUE THREAD

**Issue by mtharp** [AzureAD/microsoft-authentication-library-for-go#219]
**Which version of MSAL Go are you using?**
v0.2.0, also checked dev branch

**Where is the issue?**
* Public client
    * [x] Authorization code flow 

**Is this a new or an existing app?**
New experiment

**What version of Go are you using (`go version`)?**
go version go1.16.4 linux/amd64

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/x/.cache/go-build"
GOENV="/home/x/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/x/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/x/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/x/code/azuredemo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1775379522=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Repro**
<pre>
scopes := []string{"app://my-client-id/myscope"}
result, err := cli.AcquireTokenSilent(context.Background(), scopes, public.WithSilentAccount(account))
if err != nil {
    log.Println("silent renewal failed:", err)
    result, err = cli.AcquireTokenInteractive(context.Background(), scopes)
}
</pre>

**Expected behavior**
When the cached access_token expires, AcquireTokenSilent should use the cached refresh_token to get a new access_token with the same scopes as the original.

**Actual behavior**
The silent renewal fails with this error:
> http call(https://login.microsoftonline.com/my-client-id/oauth2/v2.0/token)(POST) error: reply status code was 400:
{"error":"invalid_request","error_description":"AADSTS90009: Application 'my-client-id'(my-client-id) is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.\r\nTrace ID: xxx\r\nCorrelation ID: yyy\r\nTimestamp: zzz","error_codes":[90009],"timestamp":"zzz","trace_id":"xxx","correlation_id":"yyy"}

**Possible solution**
The requested app:// scope is not being sent in the refresh request. I believe the problem is due to using the template b.AuthParams instead of the one filled out with the requested scope:
https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/internal/base/base.go#L235

**Comment by abhidnya13** [comment]
Hey @mtharp,

I will take a look into checking what scopes are requested using a refresh token. 

However, looking at the error being returned by AAD, I wanted to confirm the scope values you are using. Can you verify if the scope you are using is using the correct client-id, meaning the resources client id and not your own applications client id ?

**Comment by mtharp** [comment]
In this case, there is only one client ID involved. The resource is an API and the client is a command-line tool that uses the API's client ID to get an access token to authenticate to the API. The initial interactive login works fine, it's only after the initial token expires and a silent refresh is attempted that it fails because the initial scopes are not being sent.

The same thing also works fine in the javascript MSAL, including the refresh.

**Comment by abhidnya13** [comment]
@mtharp We have a similar issue in MSAL .Net linked above. If your app is both a public client application(cli tool) and a web API exposing scopes, this is  the suggestion as quoted from the above issue - 
""Token to self has a lot of buggy behavior, which is why we strongly recommend against it. We need to improve the documentation and story here, without breaking existing users of token to self. Shiung and I are tracking this, but don't have good line of sight to completion of it""

**Comment by abhidnya13** [comment]
Closing this, feel free to open if you have questions.
