### ISSUE TITLE
[Bug] Problem getting mex doc from federated url

### ISSUE THREAD

**Issue by deaborch** [AzureAD/microsoft-authentication-library-for-go#220]
**Which version of MSAL Go are you using?**
Note that to get help, you need to run the latest version. 
github.com/AzureAD/microsoft-authentication-library-for-go v0.2.0

**Where is the issue?**
* Public client
    * [ ] Device code flow
    * [X] Username/Password (ROPC grant)
    * [ ] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment

**What version of Go are you using (`go version`)?**
<pre>
$ go version
go version go1.16.4 windows/amd64
</pre>

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\abdela\AppData\Local\go-build
set GOENV=C:\Users\abdela\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\abdela\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\abdela\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.4
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\abdela\Documents\code\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\abdela\AppData\Local\Temp\go-build2929686861=/tmp/go-build -gno-record-gcc-switches
</pre></details>

**Repro**
<code>
app, err := public.New(c.ClientID, public.WithAuthority(c.Authority))
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Second)
	defer cancel()

	result, err := app.AcquireTokenByUsernamePassword(
		ctx,
		c.Scopes,
		c.Username,
		c.Password,
	)
	if err != nil {
		return nil, err
	}
return &result, nil
</code>

**Expected behavior**
Expected that when the username and password was provided to the user would be logged in

**Actual behavior**
problem getting mex doc from federated url(https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml): expected element type <definitions> but have <EntityDescriptor>

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by abhidnya13** [comment]
Hi @deaborch The mex document is not in the format MSAL understands so this error is returned when unmarshalling the xml data, what ADFS version is this authenticating with ?

**Comment by abhidnya13** [comment]
Unfortunately, username password flow is not supported for MSA accounts refer [this](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication#constraints) 

However, you can try using other public client flows - [AcquireTokenInteractive](https://github.com/AzureAD/microsoft-authentication-library-for-go/wiki/Acquiring-Token-Interactively) or [AcquireTokenByDeviceCode](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/tests/devapps/device_code_flow_sample.go)

**Comment by deaborch** [comment]
Thank you for your comment @abhidnya13. Currently trying to leverage non-interactive methods for openID connect authentication and as such both suggested methods will not work for me. Tried using the client_secret flow but this flow did not provide the information required for the openID scope (id_token). Wondering if there is a configuration I am missing in order to get that to work??

**Comment by abhidnya13** [comment]
What is the scenario you are trying to enable ? Interactive flows enable the user to get consent and also add MFA to the authentication.  There is guide to help you choose the correct authentication scenario [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview#getting-started). You also have the option of caching tokens and using AcquireTokenSilent() which will skip the interaction if it has a valid AccessToken/RefreshToken. . 

The client_secret flow, namely `AcquireTokenByCredential()` will be non interactive but this is something  to be used for deamon apps, so the identity will be an application as opposed to a user. Refer [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview#specifics). That is the reason you do not get an IDToken.There is nothing wrong with your configuration as this is by design. IDTokens contains information about a user; since there is no user here, there is no IDToken returned.

**Comment by abhidnya13** [comment]
Adding @jmprieur, @trwalke for inputs

**Comment by trwalke** [comment]
We had a similar issue [here: #2152](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2152) where we needed to modify how MSAL.NET looked into the federation metadata. We enabled MSAL to search for the correct node throughout the entire federationMetada.xml and provided an api that enabled users to provide their own federation metadata. 

The thing is, if you are using an MSA account im not sure why you would be running into this error in the first place.

Also, if you are trying to sign in noninteractively I think the only option you have is to use a work or school account with Username/Password 

@deaborch is it possible to switch to a work or school account instead?

**Comment by abhidnya13** [comment]
Hey @deaborch, do you have any updates ? Were you able to get this working ?

**Comment by deaborch** [comment]
@abhidnya13  thanks for reaching out. Managed to get the basic login flow working by creating a new user in my account and logging in using that username and password. Currently working on a different project but with some experimentation should be able to get it working. Ideally it would have been nice to have a mock framework so we wouldn't have to reach out to azure for test scenarios. Closing this issue for now.
