### ISSUE TITLE
[Bug] Client Credentials grant fails

### ISSUE THREAD

**Issue by tonyeung** [AzureAD/microsoft-authentication-library-for-go#224]
**Which version of MSAL Go are you using?**
github.com/AzureAD/microsoft-authentication-library-for-go v0.2.0

**Where is the issue?**
* Confidential client
    * [x] Client credentials:
        * [x] client secret

**Is this a new or an existing app?**
c. This is a new app or an experiment.

**What version of Go are you using (`go version`)?**

<pre>
go version go1.16.5 windows/amd64
</pre>

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\user\source\repos\project-folder\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\user\AppData\Local\Temp\go-build3526521431=/tmp/go-build -gno-record-gcc-switches

</pre></details>

**Repro**

<code>result, err := app.AcquireTokenSilent(context.Background(), config.Scopes, nil)</code>

**Expected behavior**
does not throw fatal error

**Actual behavior**
throws fatal error

**Possible solution**
Delete lines 305-307 [here](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/confidential/confidential.go#L305)
Alternatively, make it optional like how the [sample](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/tests/devapps/client_secret_sample.go#L27) implies it is.
After I deleted the file things worked fine

**Additional context / logs / screenshots**
Tried to sign the CLA to do a pull request but the instructions are crap and google results are obsolete.

**Comment by element-of-surprise** [comment]
This is simply that some old example got copied.  We went from optional structs to variadic options. You can't pass a nil variadic option.  

This has been updated an we will close this once the next release hits.
