### ISSUE TITLE
[Bug] Signed assertions fails

### ISSUE THREAD

**Issue by aramase** [AzureAD/microsoft-authentication-library-for-go#225]
**Which version of MSAL Go are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Public client
    * [ ] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [ ] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [x] Client credentials:
        * [ ] client secret
        * [ ] client certificate
        * [x] signed assertions
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**

**What version of Go are you using (`go version`)?**

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Repro**

```golang
	cred, err := confidential.NewCredFromAssertion(signedAssertion)
	if err != nil {
		klog.Fatalf("failed to create confidential creds: %v", err)
	}
	// create the confidential client to request an AAD token
	confidentialClientApp, err := confidential.New(clientID, cred,
		confidential.WithAuthority(fmt.Sprintf("https://login.microsoftonline.com/%s/oauth2/token", tenantID)))
	if err != nil {
		return errors.Wrap(err, "failed to create confidential client app")
	}

	scope := strings.TrimPrefix(resource, "/")
	if !strings.HasPrefix(scope, "/.default") {
		scope = scope + "/.default"
	}
	result, err := confidentialClientApp.AcquireTokenByCredential(ctx, []string{scope})
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).
Being able to fetch a token using the signed assertions.

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.
The token request with signed assertion fails with the following error:
```bash
FromAssertion(): http call(https://login.microsoftonline.com<tenant id>/oauth2/v2.0/token)(POST) error: reply status code was 400:
        {"error":"unauthorized_client","error_description":"AADSTS70001: Application identifier is not provided.\r\nTrace ID: 5eeb4253-adbb-435c-bdd2-24b100254300\r\nCorrelation ID: 5dab5635-09ba-4486-93a4-05dfe18b9f04\r\nTimestamp: 2021-06-18 18:59:02Z","error_codes":[70001],"timestamp":"2021-06-18 18:59:02Z","trace_id":"5eeb4253-adbb-435c-bdd2-24b100254300","correlation_id":"5dab5635-09ba-4486-93a4-05dfe18b9f04"}
```

**Possible solution**

The clientID needs to be set in the url values for [`FromAssertion`](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/internal/oauth/ops/accesstokens/accesstokens.go#L264)

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by abhidnya13** [comment]
@aramase , Thanks for reporting this, let me verify if this is the issue here, I have tested this flow e2e and it seemed to be working fine, I'll keep you posted here !

**Comment by aramase** [comment]
> @aramase , Thanks for reporting this, let me verify if this is the issue here, I have tested this flow e2e and it seemed to be working fine, I'll keep you posted here !

Thanks @abhidnya13! I've an environment with the current repro. Let me know if you want to pair.

**Comment by abhidnya13** [comment]
@aramase , I've reviewed the PR, it looks good to me. 
I did pull in the PR and saw that MSAL Go 0.1.0 was used. Client assertions was introduced in [MSAL Go 0.2.0](https://github.com/AzureAD/microsoft-authentication-library-for-go/releases/tag/v0.2.0). And you have to specify the credential as signed assertion. I have a small code snippet here to refer to : https://github.com/AzureAD/microsoft-authentication-library-for-go/wiki/Signed-Assertions#signed-assertions

[Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#second-case-access-token-request-with-a-certificate) say `client_id` as a required value, but [oauth](https://datatracker.ietf.org/doc/html/rfc7521#section-4.2) spec says its optional. Quoting it here:
```The client identifier as described in Section 2.2 of
      OAuth 2.0 [RFC6749].  The "client_id" is unnecessary for client
      assertion authentication because the client is identified by the
      subject of the assertion.  If present, the value of the
      "client_id" parameter MUST identify the same client as is
      identified by the client assertion.
```
I think you can try using 0.2.0 version without your change and see if it still gives you an error. Probably not. Regardless, I have approved your change. Can you let me know your findings if possible ?

**Comment by aramase** [comment]
> I did pull in the PR and saw that MSAL Go 0.1.0 was used

@abhidnya13 Which PR are you referring to? I'm using `github.com/AzureAD/microsoft-authentication-library-for-go v0.2.0` for trying the client assertions flow. Without `v0.2.0` I won't be able to test the client assertions. I've posted the code snippet in the issue description which defines the credential as signed assertion.

**Comment by abhidnya13** [comment]
Yes I saw the snippet you posted up here and I didn't see how the cred was initialized, so wasn't sure, if that was the issue.

**Comment by aramase** [comment]
> Yes I saw the snippet you posted up here and I didn't see how the cred was initialized, so wasn't sure, if that was the issue.
#226, when pulled was using 0.1.0 so wanted to make sure if that was causing the issue.

Gotcha! I update the issue description with the cred initialization.
