### ISSUE TITLE
[Bug] Problem with device code flow login

### ISSUE THREAD

**Issue by rickardgranberg** [AzureAD/microsoft-authentication-library-for-go#232]
**Which version of MSAL Go are you using?**
Note that to get help, you need to run the latest version. 
Microsoft Authentication Library for Go 0.2.0

**Where is the issue?**
* Public client
    * [X] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [ ] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**
This is a new app or an experiment.

**What version of Go are you using (`go version`)?**

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/patissuer/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1017103608=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Repro**
I have the problem in my code, but the same problem exists with the test app: [https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/tests/devapps/device_code_flow_sample.go](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/tests/devapps/device_code_flow_sample.go)
I've edited `config.json`, then:
<pre>
$ cd apps/tests/devapps
$ go run ./ 1
</pre>

**Expected behavior**
1. A prompt with the device code URL and the code should be presented
2. On completion of login in a browser using the above code, a token should be returned

**Actual behavior**
1. A prompt with the device code URL and the code is presented
2. On completion of login in a browser using the above code, the following error is returned:

<pre>
panic: got error while waiting for user to input the device code: http call(https://login.microsoftonline.com/c8d853de-982e-4404-92ff-b4189dc94e37/oauth2/v2.0/token)(POST) error: reply status code was 401:
{"error":"invalid_client","error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: cafa63ce-16e9-418a-869c-2171eec62200\r\nCorrelation ID: 7ce3dabb-f102-4df8-9018-036443ef846d\r\nTimestamp: 2021-06-22 12:33:02Z","error_codes":[7000218],"timestamp":"2021-06-22 12:33:02Z","trace_id":"cafa63ce-16e9-418a-869c-2171eec62200","correlation_id":"7ce3dabb-f102-4df8-9018-036443ef846d","error_uri":"https://login.microsoftonline.com/error?code=7000218","claims":"{\"access_token\":{\"capolids\":{\"essential\":true,\"values\":[\"348e00dd-9a6d-4fac-a01f-2d267b4ecfd4\"]}}}"}

goroutine 1 [running]:
main.acquireTokenDeviceCode()
        <path>/microsoft-authentication-library-for-go/apps/tests/devapps/device_code_flow_sample.go:46 +0xacc
main.main()
        <path>/microsoft-authentication-library-for-go/apps/tests/devapps/main.go:16 +0x9c
exit status 2
</pre>

It looks to me that I should be using the `confidential.Client` for this, but that does not implement the `AcquireTokenByDeviceCode` func
**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by abhidnya13** [comment]
Hey @rickardgranberg, 

Device code flow is only supported on public client applications. Can you make sure your configuration on Azure Portal has enabled public client flows : 
![issue_1_msalgo](https://user-images.githubusercontent.com/12730799/123139346-faf42d80-d40a-11eb-970a-6c83bc5fcb0c.PNG)

**Comment by rickardgranberg** [comment]
Ah! I assumed the issue was caused by a setting but couldn't find it! Thank you!
