### ISSUE TITLE
[Bug] Device code flow doesn't work when we provide tenantID as `common` in the authority url

### ISSUE THREAD

**Issue by himanshutyagi36** [AzureAD/microsoft-authentication-library-for-go#238]
**Which version of MSAL Go are you using?**
v 0.3.0

**Where is the issue?**
* Public client
    * [x] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [ ] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**
We at the Ev2 team have a Go cli client. We moved from adal to msal 2 months ago and were using the AquireTokenInteractive() flow. The issue started showing up when we also integrated the `AcquireTokenByDeviceCode()`
-->

**What version of Go are you using (`go version`)?**
1.15.2

**What operating system and processor architecture are you using (`go env`)?**
Our cli is used in Windows, Linux and Mac. For my testing, I'm using windows.

**Repro**
Following is the relevant code excerpt.
If I use the following when creating public client app, `AquireTokenInteractive()` works and `AquireTokenByDeviceCode()` fails
<code>
       authorityURL := "https://login.microsoftonline.com/common"
</code>

If I use the following, both `AquireTokenInteractive()` and `AquireTokenByDeviceCode()` work.
<code>
       authorityURL := "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47"
</code>

**Expected behavior**
`AquireTokenByDeviceCode()`  authentication flow should work with generic tenantID `common` in the authorityUrl for public client.

**Actual behavior**
`AquireTokenByDeviceCode()` authentication flow fails when using generic tenantID `common` in the authorityUrl for public client, with following error (probably returned from AAD)
Error: 
```
Error: http call(https://login.microsoftonline.com/common/oauth2/v2.0/devicecode)(POST) error: reply status code was 400:
{
    "error": "invalid_request",
    "error_description": "AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 73c53c41-2853-4e8d-928d-baa978a74600\r\nCorrelation ID: 7b82ae7d-7b59-48c6-9ff6-af5d6bf3bd9d\r\nTimestamp: 2021-06-26 00:01:36Z",
    "error_codes": [
        50059
    ],
    "timestamp": "2021-06-26 00:01:36Z",
    "trace_id": "73c53c41-2853-4e8d-928d-baa978a74600",
    "correlation_id": "7b82ae7d-7b59-48c6-9ff6-af5d6bf3bd9d"
}
```

**Possible solution**
Before `msal`, we were using the azure-sdk-for-go auth package, which was based on Adal. We didn't have any issues in authentication when using tenantID == `common`  with that. 

**Additional context / logs / screenshots**
The reason we want to use the generic tenantID is to be able to authenticate with Corp, AME, Sovereign clouds devops tenant, Sovereign clouds Prod tenants etc.

**Comment by abhidnya13** [comment]
@himanshutyagi36 , for sovereign clouds, the authority instance to be used is different as well. 
For example, US government authority looks like this - `login.microsoftonline.us`
Refer this for enabling sovereign clouds scenario: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud#azure-ad-authentication-endpoints

**Comment by himanshutyagi36** [comment]
@abhidnya13 Yes, the base authority url will be different, I posted the one above just as an example for Public clouds, that's not the issue is though. 
The authority url is of the format: `https://base_url/tenantID`, the issue I'm trying to bring up is the `tenandID` part of the authority url, when using device code flow, only works when we provide actual tenant guid and not the generic tenantID `common`, whereas for interactive auth flow, we face no such issues.
The ask here is for device code flow of msal/go to work with tenantID as `common` and not a particular guid.

**Comment by abhidnya13** [comment]
If this is a multi-tenant application, `common` is supposed to work and I just tested that it works as expected.
If this is a single tenant application, you will have to specify the tenant id as there is only one tenant involved. 
Your application can be multi-cloud but single tenant. 
I am unable to reproduce this at the moment. Can you provide a repro ?

**Comment by himanshutyagi36** [comment]
@abhidnya13 You are correct. The issue seems to be just for single tenant application. I tried with our multi tenant applications and the device code flow worked fine with tenantID as `common`

**Comment by abhidnya13** [comment]
You will need to provide the `tenantID` if your app is a single tenant app.

**Comment by abhidnya13** [comment]
After confirming with @himanshutyagi36 offline, this has been resolved.
