### ISSUE TITLE
[Feature Request] Known authorities supported in MSAL

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#253]
Internal [epic](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/823221)
Refer [this](https://microsoft.sharepoint.com/:w:/t/aad/devex/EWC3mswvQuxJuFpoTY1S9g8B288C1AKhE7iXonJ5DHBWaA?e=YNJpRH)

**Comment by bgavrilMS** [comment]
Feature superseeded by `WithInstanceMetadata(false)`. Therefore won't fix https://github.com/AzureAD/microsoft-authentication-library-for-go/commit/dac2c13522a7c85a08d7f31e52477b5e357834de
