### ISSUE TITLE
[Feature Request] Remove Client library dependency on hardcoded endpoints in isolated clouds by improving authority validation 

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#254]
Internal [epic](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1042138)

**Comment by bgavrilMS** [comment]
Fixed by https://github.com/AzureAD/microsoft-authentication-library-for-go/commit/dac2c13522a7c85a08d7f31e52477b5e357834de
