### ISSUE TITLE
[Feature Request] MSAL has a capability to send clientName and version of the app to ESTS

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#262]
SDK consistency : https://identitydivision.visualstudio.com/Engineering/_workitems/edit/865186

Ensure x-app-name and x-app-ver are sent to the same end-points as other x-client- params.
Let the developer specify the app name and the app version

**Comment by jennyf19** [comment]
Not needed, as ESTS never did the work on their end, so no need to send these values.
