### ISSUE TITLE
Can't send certificate chain in SNI authentication

### ISSUE THREAD

**Issue by chlowell** [AzureAD/microsoft-authentication-library-for-go#267]
I observe NewCredFromCert takes a single `*x509.Certificate` (although CertFromPEM returns `[]*x509.Certificate`). `Credential` therefore carries a single cert, making it impossible to send a chain via the "x5c" header, as allowed by [RFC 7515](https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.6). Does AAD require only the leaf cert?

(Related: #122)

**Comment by henrik-me** [comment]
Both should be supported and it is supported in Java already afair. Marking as feature request.

**Comment by rayluo** [comment]
> Does AAD require only the leaf cert?

I'm almost one year late to the party ... But the answer is AAD supports multiple certs.
