### ISSUE TITLE
confidentialClientApp.AcquireTokenSilent ignores the cases sensitivity of the scopes

### ISSUE THREAD

**Issue by bagajjal** [AzureAD/microsoft-authentication-library-for-go#268]
Using MSAL 0.3.0. 
Hyrid agent calls the confidentialClientApp.AcquireTokenSilent () with scope set to "https://pas.windows.net/CheckMyAccess/Linux".
MSAL returned token has the audience with lower case i.e, https://pas.windows.net/checkmyaccess/linux. This causes the PAS request to fail as PAS has a case sentitive check for the audience field in the MSI token.

Steps to repro -
1) Onboard a machine as arc machine.
2) Run these commands to get the MSI 
ChallengeTokenPath=$(curl -s -D - -H Metadata:true "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https://pas.windows.net/CheckMyAccess/Linux" | grep Www-Authenticate | cut -d "=" -f 2 | tr -d "[:cntrl:]")
ChallengeToken=$(sudo cat $ChallengeTokenPath)

curl -s -H Metadata:true -H "Authorization: Basic $ChallengeToken" "http://127.0.0.1:40342/metadata/identity/oauth2/token?api-version=2019-11-01&resource=https://pas.windows.net/CheckMyAccess/Linux"

![image](https://user-images.githubusercontent.com/23668037/133858717-070b9265-c956-4a99-82d6-21bd8fb65044.png)

I'm Microsoft FTE. You can ping me on teams, if you need more information.

**Comment by abhidnya13** [comment]
Resolved in [MSAL Go 0.3.1 ](https://github.com/AzureAD/microsoft-authentication-library-for-go/releases/tag/v0.3.1)
