### ISSUE TITLE
can not find token in cache. 

### ISSUE THREAD

**Issue by linneawang** [AzureAD/microsoft-authentication-library-for-go#272]
https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/b2c5228ae9dbb13ea743074fea59fa721c61fa1b/apps/internal/base/base.go#L304

shouldn't this 
`suggestedCacheKey := b.AuthParams.CacheKey(false)`
be 
`suggestedCacheKey := authParams.CacheKey(false)`

in many cases we've found that `suggestedCacheKey` is empty string therefore can't find token in our local cache.

**Comment by abhidnya13** [comment]
Closing this, feel free to re-open if needed.
