### ISSUE TITLE
Review logging

### ISSUE THREAD

**Issue by hchittanuru3** [AzureAD/microsoft-authentication-library-for-go#28]
Make sure to review what is being logged

**Comment by bgavrilMS** [comment]
I have some guidance around logging here: https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/7325?_a=files&path=/PII/pii%20handling.md

I'm happy to review this one.

**Comment by chlowell** [comment]
Closed by #382
