### ISSUE TITLE
access token verifcation

### ISSUE THREAD

**Issue by nbraun-wolf** [AzureAD/microsoft-authentication-library-for-go#282]
Hi, I am interested in verification of tokens. If a token was acquired by a frontend, for example, and is sent to a backend service, I need to verify that the token is valid and read its claims.

It would be nice if there were methods like verify, which takes a client secret and verifies the token and potentially another method like parse which decodes the token so that the claims can be read.

Are there any options to do this? I could not identify something while looking at the code.

**Comment by abhidnya13** [comment]
MSAL Go is a token acquisition and caching library, and not a token validation library. Generally, what you'd need to do is send the access_token (one that was issued specifically to access your application) to your back-end service in a header (Authorization: Bearer <access-token>) along with your request.

It's then the responsibility of the BE service to validate the token. It must verify at least the following assertions about the access token:

- that its aud (audience) claim is that of the backend service.
- that its iss (issuer) claim is Azure AD or one of its aliases.
- that it signature confirms it is signed by valid Azure AD signing keys (or custom signing keys if your app has configured it as such).
- That it is currently valid (not yet past its exp claim, not before its nbf claim).

Next, you must assert any other claim(s) that are specific to your app and require custom validation (e.g., scopes)

You can start [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens) for a guide on how to validate access tokens from your back-end service.

**Comment by nbraun-wolf** [comment]
OK, thanks for the info. I did verify the token by other means. I think it would be a good features for this library.
