### ISSUE TITLE
[Feature Request] ValidateAuthority parameter not exposed causing the library not to be used in ADFS deployment.

### ISSUE THREAD

**Issue by rjaini** [AzureAD/microsoft-authentication-library-for-go#289]
[Feature Request] ValidateAuthority parameter not exposed causing the library not to be used in ADFS deployment.

Because of above limitation the library cannot be used on ADFS based Azure Stack Hub deployment.

**Comment by henrik-me** [comment]
ADFS not yet supported in MSAL go. Feature: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/31

Will need to explore timeline. 
CC: @abhidnya13

**Comment by chlowell** [comment]
Related: #301. It may be better to add something like MSAL for JS's known authorities than to expose ValidateAuthority.

**Comment by chlowell** [comment]
Authority validation must be enabled by default to prevent applications from sending credentials to a malicious server.

**Comment by chlowell** [comment]
Closed by #362, which added a [`WithInstanceDiscovery()`](https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-library-for-go/apps/confidential#WithInstanceDiscovery) option
