### ISSUE TITLE
[Feature Request] UserPrincipalName parameter is not expose in confidential/public classes causing API to fail on ADFS env

### ISSUE THREAD

**Issue by rjaini** [AzureAD/microsoft-authentication-library-for-go#291]
UserPrincipalName parameter is not expose in confidential/public classes causing API to fail on ADFS env

The code https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/internal/base/base.go is passing blank value and not exposed to upper class cases failure in https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/apps/internal/oauth/resolvers.go#L48 code location

**Comment by henrik-me** [comment]
ADFS not yet supported in MSAL go. Feature: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/31

Will need to explore timeline. 
CC: @abhidnya13

**Comment by bgavrilMS** [comment]
Supported added in 0.8.1 - just add `WithInstanceDIscovery(false)` and it will work.
