### ISSUE TITLE
[Feature Request] Enable changing tenant after client construction

### ISSUE THREAD

**Issue by chlowell** [AzureAD/microsoft-authentication-library-for-go#296]
Acquiring tokens as a multi-tenant application is painful because tenants are baked into clients at construction. It's therefore necessary to create a new client instance for each tenant. Please provide an API for overriding the tenant specified at construction during a single token request or enable changing it after construction. MSAL.NET has implemented the former and is evidently moving to the latter:  https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/368#issuecomment-945631545.

**Comment by henrik-me** [comment]
@bgavrilMS @siddhijain @rayluo : can you pls. help with the per request design?

**Comment by bgavrilMS** [comment]
In pseudo-code, the logic in MSAL.NET is something like: 

```csharp

var confidentialClientApp = // create app with authority set to login.microsoft.com/common

var authResult = confidentialClientApp.AcquireTokenByMethod.WithTenantId(tenantId).Execute();
```

The simplified algorithm for choosing the authority on which to perform auth, given an **application** authority and a **request** tenantID is:

- if config authority is not set, use app authority
- if request.tenantId is configured and app.Authority is not AAD, throw an exception (only AAD supports tenants)
- if request.tenantId is "common" or "organizations", throw an exception (the API is for forcing an actual tenantid)

The more complex case exists for AcquireTokenSilent, where we can also need to think about `Account.HomeTenantId`. I am not 100% sure if MSAL Go's `AcquireTokenSilent(account)` uses account.HomeTenantId, but if it does then if all 3 options are specified, the same as above apply, and prefer to use `request.tenantId` and not `account.homeTenant.Id`

## Acceptance tests

| app.Authority     | request.TenantId | Account.HomeTenantid | Expected Authority |
|-------------------|------------------|----------------------|-------------------|
| lmo/common        | GUID             |                      | lmo/GUID          |
| lmo/organizations | GUID             |                      | lmo/GUID          |
| lmo/consumers     | GUID             |                      | lmo/GUID          |
| lmo/GUID1     | GUID2             |                      | lmo/GUID2         |
| lmo/GUID    | common or organizations |           null or any           | ERROR   |
| lmo/GUID1    | GUID2 |  GUID3                    | lmo/GUID2  |
| lmo/common|  |              GUID        | lmo/GUID |

**Comment by rayluo** [comment]
> 
> | app.Authority     | request.TenantId | Account.HomeTenantid | Expected Authority |
> |-------------------|------------------|----------------------|-------------------|
> | lmo/common        | GUID             |                      | lmo/GUID          |
> | lmo/organizations | GUID             |                      | lmo/GUID          |
> | *lmo/consumers*     | *GUID*             |                      | *lmo/GUID*          |

Hi @bgavrilMS , in the table above, row 3, if an app declared its authority as "lmo/consumers", wouldn't it mean the app does not want to allow AAD users to sign in? Do we still want to allow the guid adjustment in this scenario?

**Comment by bgavrilMS** [comment]
Now that you mention it, yes. I don't think MSAL.NET does any better :(

**Comment by chlowell** [comment]
MSAL for Go will have a few rules for dynamic tenant IDs as described in this issue (implemented [here](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/343/files#diff-09137129f4a8c35929c587580afc33ae3033e1efb10e76db33196c2f25d50bf0R174)) but otherwise no opinion on their validity. So, we'll take any string and it's up to AAD whether it works. `WithTenantID("contoso.onmicrosoft.com")` will make the request URL `https://authority/contoso.onmicrosoft.com/...`

**Comment by rayluo** [comment]
Well, in that case, it is really just a "WithTenant(tenant)" parameter, rather than "WithTenantId(tenantId)" which seemingly implies a GUID. Thanks for the clarification.

**Comment by chlowell** [comment]
That's correct. I assume it's the same for the other MSALs which call the option `WithTenantID`. Is semantic accuracy more important than consistency with those MSALs?

**Comment by rayluo** [comment]
I believe the consistency is more about Conceptual Consistency: if one thing can and should be done in one MSAL, other applicable MSALs would better also have it. But the exact naming always has some variance, due to language convention and casing reasons. In particular, already-shipped parameters do not need to be changed only for consistency, and newly-introduced parameter in an MSAL has an opportunity to "name it right", if desirable.

I'm leaving an approval to your implementation PR now.

**Comment by Joon-L** [comment]
Hello @rayluo, is there a plan to release a new package version with the WithTenantID support changes? Meanwhile if we want to acquire tokens for multiple tenants is the workaround to create client per tenant?

**Comment by bgavrilMS** [comment]
Yes, create a confidential client application for each tenant / authority you have.

**Comment by Joon-L** [comment]
Got it. Thank you for confirming. It would be ideal if we could avoid this with the new changes. When could we expect a new release version with this change?
