### ISSUE TITLE
Add support for Integrated Windows Authentication

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-go#30]

**Comment by a114383** [comment]
Appreciate all the work on this library so far, how easy it is to be cross platform is great!   We have some windows users looking for this feature though.  

I searched this repo and see [a few references to "integrated"](https://github.com/AzureAD/microsoft-authentication-library-for-go/search?q=integrated) and I was hoping maybe this got implemented and just not documented?

**Comment by bgavrilMS** [comment]
@a114383 - Username/Password uses SAML if the user is a federated ADFS user. Similar to IWA flow. But IWA itself is not implemented.

**Comment by bgavrilMS** [comment]
We should avoid this, in favor of using WAM / PRTs.
