### ISSUE TITLE
Consistency track: please provide consistent APIs to disable authority validation and instance discovery

### ISSUE THREAD

**Issue by xiangyan99** [AzureAD/microsoft-authentication-library-for-go#301]
MSAL Go has no API for this now but when it does, this is only to track the work and to be sure it's consistent with MSAL best practice

**Comment by jennyf19** [comment]
@xiangyan99 Can you provide some examples of which APIs you are referring to? Thanks.

**Comment by xiangyan99** [comment]
FYI. In msal Python, when creating ClientApplication, we can opt out validate_authority to false. https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/application.py#L164.

User can use it when they want to use a private authority.

.net, java, js have similar functionalities but we have not yet added this support for go.

**Comment by henrik-me** [comment]
potentially dupe of: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/289

**Comment by chlowell** [comment]
Closed by #362, which added a `WithInstanceDiscovery()` option
