### ISSUE TITLE
Azure - Authenticator

### ISSUE THREAD

**Issue by Jyliew94** [AzureAD/microsoft-authentication-library-for-go#303]
**Which version of MSAL Go are you using?**
Note that to get help, you need to run the latest version. 

**Where is the issue?**
* Public client
    * [ ] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [ ] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**

**What version of Go are you using (`go version`)?**

<pre>
$ go version
</pre>

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Repro**

<code>var your = (code) => here;</code>

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Actual behavior**
A clear and concise description of what happens, e.g. an exception is thrown, UI freezes.

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jennyf19** [comment]
@Jyliew94 I'm not seeing any content outside of the issue template, going to close, but please reopen with necessary info. Thanks!
