### ISSUE TITLE
Add support for ADFS2019

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-go#31]
[Microsoft Docs ADFS documentation](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)

**Comment by bgavrilMS** [comment]
This is complete via https://github.com/AzureAD/microsoft-authentication-library-for-go/commit/dac2c13522a7c85a08d7f31e52477b5e357834de.

 App developers must explicitly disable instance discovery using `WithInstanceDiscovery(false)`

**Comment by bgavrilMS** [comment]
Fixed in 0.8.1
