### ISSUE TITLE
TenantDiscoveryEndpointWithRegion format is wrong

### ISSUE THREAD

**Issue by northtyphoon** [AzureAD/microsoft-authentication-library-for-go#320]
The following TenantDiscoveryEndpointWithRegion endpoint only works for public cloud. It doesn't work for national cloud or ppe environment. 

https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/d54fcb30bf81362a21e46cfd87bca0e5e73f77fb/apps/internal/oauth/ops/authority/authority.go#L25

I talked to ests team and confirmed the expected endpoint working for all clouds is 

https://%v.%v/%v/v2.0/.well-known/openid-configuration, eg, 

Prod: https://westus2.login.microsoft.com/common/v2.0/.well-known/openid-configuration
PPE: https://westus2.login.windows-ppe.net/common/v2.0/.well-known/openid-configuration
USGov: https://usgovvirginia.login.microsoftonline.us/common/v2.0/.well-known/openid-configuration
China: https://chinanorth3.login.partner.microsoftonline.cn/common/v2.0/.well-known/openid-configuration

**Comment by bgavrilMS** [comment]
That looks correct, although the prod endpoint is `{region}.r.login.microsoftonline.com`. I think `{region}.login.microsoft.com` works as well, and ESTS-R want us to move to it soon, but right now the `r.login` version is preffered.

**Comment by rayluo** [comment]
This issue is fixed by #321.
