### ISSUE TITLE
[Bug] v0.6.0 is backwards-incompatible with v0.5.3

### ISSUE THREAD

**Issue by Justin-W** [AzureAD/microsoft-authentication-library-for-go#341]
**Which version of MSAL Go are you using?**
Note that to get help, you need to run the latest version. 

github.com/AzureAD/microsoft-authentication-library-for-go@v0.6.0

**Where is the issue?**
* Public client
    * [ ] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [ ] Authorization code flow 
* Confidential client
    * [ ] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

a "panic: runtime error: invalid memory address or nil pointer dereference" panic occurs at https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/a04b7709039511fc3de4594aced243090c1973a9/apps/internal/oauth/ops/accesstokens/accesstokens.go#L141

**Is this a new or an existing app?**

The app is in production and I have upgraded to a new version of Microsoft Authentication Library for Go.

**What version of Go are you using (`go version`)?**

<pre>
$ go version
go version go1.18.4 darwin/arm64
</pre>

**What operating system and processor architecture are you using (`go env`)?**

This occurs on both darwin/mac, and also linux.

**Repro**

```go
	testMSP := NewMSAuthProvider(nil)
	t.Run("keystoreCertError", func(t *testing.T) {
		req := &oauth2.TokenRequest{Code: code, Redirect_URI: redirectURI, ClientId: clientID, KeyStores: keystores}
		_, err := testMSP.AcquireTokenByAuthCode(context.TODO(), req)
		require.Error(t, err)
	})
```

**Expected behavior**
Calling `AcquireTokenByAuthCode` should not cause a panic (even if `Certificate.Cert` is nil)).

**Actual behavior**
Calling `AcquireTokenByAuthCode` with bad inputs causes a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1010d5d4c]
```

**Possible solution**

With v0.5.3, the func call returned an error as expected. With v0.6.0, it causes a panic.

The panic occurs when https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/a04b7709039511fc3de4594aced243090c1973a9/apps/internal/oauth/ops/accesstokens/accesstokens.go#L123 passes `nil` to the `thumbprint` func, resulting in a panic at https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/a04b7709039511fc3de4594aced243090c1973a9/apps/internal/oauth/ops/accesstokens/accesstokens.go#L141.

The root cause seems to be that PR #319 removed this guard code:

https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/c4784476597b55a050e37971dac2bb396f601938/apps/internal/oauth/ops/accesstokens/accesstokens.go#L114-L120

, which previously (in v0.5.3) prevented a Credential with a nil Cert from reaching the code which now panics in v0.6.0.

The solution would seem to be to re-add guard code which ensures that the panicing func handles bad input/state gracefully (without panicing). 

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots.

**Comment by chlowell** [comment]
Thanks for opening this! I'll open a PR to prevent this panic. It's not clear to me how it would occur in ordinary usage though. Can you share code for `NewMSAuthProvider`?

**Comment by Justin-W** [comment]
> Thanks for opening this! I'll open a PR to prevent this panic. It's not clear to me how it would occur in ordinary usage though. Can you share code for `NewMSAuthProvider`?

@chlowell Here it is:

```go
type MSProvider struct {
	AuthProvider MSAuthProvider
	creds        *Credential // for testing
	clt          client.GrpcClient
}

func NewMSAuthProvider(clt client.GrpcClient) (msp *MSProvider) {
	if clt == nil {
		clt = grpc.GetSharedGrpcClient()
	}
	msp = &MSProvider{
		clt: clt,
	}
	return msp
}
```

We have some tests which exercise various error condition scenarios (to make sure that our code also handles those scenarios correctly), and one of those triggered the panic. Not sure whether any other code of ours would also possibly trigger the same panic through "normal" usage, as we downgraded back to v0.5.3 due to the failing test.

**Comment by Justin-W** [comment]
> I opened #342 to prevent this and related panics by having `confidential.New()` return an error when given an invalid `confidential.Credential`, which I believe is what your test is doing (please correct me if I'm wrong about that 😊). This is a behavior change vs 0.5.3 in that some authentication errors will now be constructor errors instead, so your test may still need an update.

Thanks for the quick response. That seems like it should work. I think our current tests are merely asserting that an err is returned, and will still work even if a different error is returned. Either way, as long as it returns an err and doesn't panic, we can update our tests as needed. Any idea when v0.6.1 will be released with the fix?
