### ISSUE TITLE
[Feature Request] Switch regional on public client to use <region>.login.microsoft.com instead of <region>.r.login.microsoftonline.com

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-go#361]
See https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2165936 for details.

**Comment by element-of-surprise** [comment]
Fixed with: https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/408
