### ISSUE TITLE
[Documentation] CreateAuthCodeURL Naming Consistency

### ISSUE THREAD

**Issue by dannmartens** [AzureAD/microsoft-authentication-library-for-go#371]
### Documentation related to component

Inconsistent method naming across confidential and public Clients:
 AuthCodeURL vs. CreateAuthCodeURL

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

confidential:
```
[func (cca Client) AuthCodeURL(ctx context.Context, clientID, redirectURI string, scopes []string) (string, error)](https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-library-for-go@v0.7.0/apps/confidential#Client.AuthCodeURL)
```

public:
```
[func (pca Client) CreateAuthCodeURL(ctx context.Context, clientID, redirectURI string, scopes []string) (string, error)](https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-library-for-go@v0.7.0/apps/public#Client.CreateAuthCodeURL)
```

While I report this as a documentation issue, fixing this obviously will cause an API change.

**Comment by chlowell** [comment]
Thanks for opening this issue! We decided to change the API and will rename `CreateAuthCodeURL` to `AuthCodeURL` in the next version.
