### ISSUE TITLE
API changes for GA release

### ISSUE THREAD

**Issue by chlowell** [AzureAD/microsoft-authentication-library-for-go#380]
# API changes since v0.8.0

Upgrading from v0.8.* may require code changes as described below.

## `confidential.New` requires an authority [#394](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/394)

`confidential.WithAuthority` has been deleted, and the URL it set is now a parameter of `confidential.New` :

```go
// before
client, err := confidential.New(clientID, cred, confidential.WithAuthority(authority))

// after
client, err := confidential.New(authority, clientID, cred)
```

## `confidential.NewCredFromCertChain` replaces `NewCredFromCert` [#391](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/391)

If your application calls `NewCredFromCert`, update arguments and return values:

### before

```go
certs, key, err := confidential.CertFromPEM(certData, password)
if err != nil {
    // TODO: handle error
}
cred := confidential.NewCredFromCert(certs[0], key)
```

### after

```go
certs, key, err := confidential.CertFromPEM(certData, password)
if err != nil {
    // TODO: handle error
}
cred, err := confidential.NewCredFromCert(certs, key)
if err != nil {
    // TODO: handle error
}
```

If your application calls `confidential.NewCredFromCertChain`, call `NewCredFromCert` instead.

## All methods accessing cache data have a `Context` parameter [#378](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/378)

For example, `RemoveAccount` and `Accounts`:

```go
// before
accounts, err := client.Accounts()

// after
accounts, err := client.Accounts(context.TODO())
```

## Renamed functions

These functions are renamed but otherwise unchanged:

- `confidential.NewCredFromCertChain` -> `NewCredFromCert` [#391](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/391)
- `confidential.WithAccessor` -> `WithCache` [#386](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/386)
- `public/Client.CreateAuthCodeURL` -> `AuthCodeURL` [#384](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/384)

## Deleted API

- `confidential.NewCredFromAssertion`. This function was deprecated in v0.6.0; use `confidential.NewCredFromAssertionCallback` instead [#385](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/385)
- Unused options types such as `public.InteractiveAuthOption` and `confidential.AcquireTokenSilentOptions`. [#383](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/383), [#390](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/390)
- `confidential/Client.UserID`. The value was always `""` and never used by the client. [#389](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/389)

## New `cache.ExportReplace` parameters

The interface for custom cache implementations has new parameters for `Context` and metadata ([#378](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/378), [#395](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/395)).

**Comment by grantjoy** [comment]
This is really misleading as it's not mentioned in the docs but it has to be implemented in this new format. All the examples I could find were incorrect.

**Comment by bgavrilMS** [comment]
Well, we GA-ed so I guess this can be closed.
