### ISSUE TITLE
Check log messages for Pii

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-go#39]
ex. u/p w/`common` instead of `organizations`

**Comment by henrik-me** [comment]
Even though it's a duplicate to some extend, I think it's great to have a special focus on properly marking the right things for PII, where as #28 to me is more about the functionality of being able to log, with and without PII

**Comment by element-of-surprise** [comment]
All logging has been removed from the packages.  We now return our information in messages, where the user has the choice to log or not log with whatever logging package they want.  

If you want to change this to scrubbing error messages, then please reopen with a different title.
