### ISSUE TITLE
[Feature Request] Gain optional claims from IDToken

### ISSUE THREAD

**Issue by jkroepke** [AzureAD/microsoft-authentication-library-for-go#400]
**Is your feature request related to a problem? Please describe.**
I have configured optional claims on my app registration. After calling `result, err := devCode.AuthenticationResult(ctx)`, the claim is part of the IDToken, but not accessible through the go struct.

**Describe the solution you'd like**
Make all optional claim available as struct Field. 

**Describe alternatives you've considered**
Use the [`AdditionalFields`](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/9a63cc219c3822f23f3a54c62c1261b729a50536/apps/internal/oauth/ops/accesstokens/tokens.go#L42) field for non-defined fields.

**Comment by bgavrilMS** [comment]
Why not use the `AdditionalFields` ? I don't think we should be adding explicit support for a subset of optional claims.

Besides, I believe AAD already has Conditional Access policies to prevent or force MFA based on IP address..
