### ISSUE TITLE
[Bug] confidential.WithAuthority is undefined

### ISSUE THREAD

**Issue by isabellachen** [AzureAD/microsoft-authentication-library-for-go#418]
**Which version of MSAL Go are you using?**
v1.0.0

**Where is the issue?**
* Confidential client
    * [X] Authorization code flow 
    * [ ] Client credentials:
        * [ ] client secret
        * [ ] client certificate
* Token cache serialization
     * [ ] In-memory cache
* Other (please describe)

**Is this a new or an existing app?**
This is a new app

**What version of Go are you using (`go version`)?**

<pre>
$ go version go1.20.1
</pre>

**What operating system and processor architecture are you using (`go env`)?**
darwin/arm64

**Repro**
<img width="1723" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-go/assets/9280665/e9246682-0909-4a18-9aaa-cf0e75c0057a">

<img width="994" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-go/assets/9280665/ef2299f5-cbbe-451f-9e14-16561a8c8301">

**Expected behavior**
I am following the docs to set up a confidential client app: https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-library-for-go@v1.0.0#section-readme

Sadly WithAuthority does not exist in the confidential package.

**Comment by isabellachen** [comment]
Hmm, I think this is more a documentation thing. The args for `confidential.New()` are different from the documentation on the main page. 

Would this be the right?
```go
func (a *authorizationHandlers) GetPowerBIEmbedToken(w http.ResponseWriter, r *http.Request) {
	cred, err := confidential.NewCredFromSecret("client_secret")
	if err != nil {
		fmt.Errorf("could not create a cred from a secret: %w", err)
	}

	confidentialClientApp, err := confidential.New(
		"https://login.microsoftonline.com/<your tenant>",
		"powerBI_clientID",
		cred,
	)
}
```

**Comment by isabellachen** [comment]
It works. I guess the docs need to be updated.

**Comment by isabellachen** [comment]
I suppose its more a docs need to be fixed rather than a bug. I was able to create the confidential client app with the code I shared above.

**Comment by kunKun-tx** [comment]
> I suppose its more a docs need to be fixed rather than a bug. I was able to create the confidential client app with the code I shared above. Looks like they have removed the .WithAuthority method.

Yes, upgraded from ver.7 and had the same issue. Didn't find anything in the release note but your post is very helpful.
