### ISSUE TITLE
[Documentation] Example for creating a confidential client are incorrect

### ISSUE THREAD

**Issue by kevindixon** [AzureAD/microsoft-authentication-library-for-go#421]
### Documentation related to component
Usage (README.md)

### Please check all that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in the example
- [ ] needs an example

### Description of the issue

Creation of a confidential client is documented as: 

```
confidentialClientApp, err := confidential.New("client_id", cred, confidential.WithAuthority("https://login.microsoft.com/Enter_The_Tenant_Name_Here"))
```

However, this doesn't match the function signature of `confidential.New()` which is:

```
func New(authority, clientID string, cred Credential, options ...Option) (Client, error)
```

So:
- `authority` is missing
- `confidential.WithAuthority` doesn't exist

See also #418

**Comment by quynhduongphl** [comment]
seems like this is seriously outdated, WithAuthority has been removed a while ago.
