### ISSUE TITLE
Contributing instructions should explain when to target dev or main branch

### ISSUE THREAD

**Issue by hickford** [AzureAD/microsoft-authentication-library-for-go#430]
The repo has default branch 'dev' as well as another branch 'main' which is confusing because 'main' is the default branch in most projects. [CONTRIBUTING.md](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/CONTRIBUTING.md#decide-on-which-branch-to-create) should explain the purpose of the branches and which to target from PRs. Is one branch for bug fixes and the other for new features?

The current instructions add to the confusion:

> Bug fixes for the current stable version need to go to 'master' branch.

There isn't any master branch!

**Comment by bgavrilMS** [comment]
We now moved away from dev branch and only main branch is active.

**Comment by hickford** [comment]
You still need to correct https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/CONTRIBUTING.md#decide-on-which-branch-to-create

> Bug fixes for the current stable version need to go to 'master' branch.
