### ISSUE TITLE
Issue with AcquireTokenInteractive - AADSTS9002327 caused due to missing headers

### ISSUE THREAD

**Issue by Ahmed-hassan99** [AzureAD/microsoft-authentication-library-for-go#494]
### Issue with AcquireTokenInteractive
I was trying to use AcquireTokenInteractive functionality to get a token for a SPA, I believe the issue is caused by missing headers when sending the token request after retrieving the authentication code. 

### Error Message
AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.

### Cause of Error
Headers missing 

Origin: http://localhost

https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/004301ceccb1206100a19cae1a6a4e4e37be8b20/apps/internal/oauth/ops/internal/comm/comm.go#L192-L195

### Similar Issue in Js library 
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2482

**Comment by bgavrilMS** [comment]
SPA scenarios are only supported by MSAL Javascript @Ahmed-hassan99
