### ISSUE TITLE
[Bug] Instance discovery cache is not thread safe

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/microsoft-authentication-library-for-go#52]
**Where is the issue?**
* Other (please describe)

AadInstanceDiscovery uses a private global for it's cache but does not synchronize read and writes.

**Expected behavior**
Instance discovery cache is thread safe

**Actual behavior**
Instance discovery cache is not thread safe

**Other
sync.Once isn't really needed here either as the only thing it does is init a var, which can be done in it's declaration.

**Comment by element-of-surprise** [comment]
The re-write removed these globals.  We are not seeing anything with the race detector.  Closing this out.
