### ISSUE TITLE
[Bug] Should use method on uuid that errors instead of panics

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/microsoft-authentication-library-for-go#53]
**Where is the issue?**
* Other (please describe)

github.com/google/uuid.New() returns a new uuid or panics, instead should use NewRandom() and handle the error appropriately

See: https://godoc.org/github.com/google/uuid#New

**Comment by abhidnya13** [comment]
@keegan-caruso , Looked up the cases where NewRandom() can error. Apparently it uses a rand.Reader which is where the error might originate as it calls certain kernel functions. Reference for this is [here](https://stackoverflow.com/a/47433983/9700346). [This](https://github.com/google/uuid/blob/bd451584982ecf4ca5b1e5938cf168e17e30d837/version4.go#L29) is the code blob to refer to.

It should be fine letting it panic as it would happen in very rare cases. Let me know if you still have any concern.

**Comment by keegan-caruso** [comment]
Thanks for looking into it!
