### ISSUE TITLE
Review all third-party dependencies

### ISSUE THREAD

**Issue by jhendrixMSFT** [AzureAD/microsoft-authentication-library-for-go#55]
We (the Go SDK team) have been burned in the past by poor-quality third-party dependencies.  Review the current list to ensure they're required and provide value.

We should also avoid using any third-party type as an "exchange type" (a type exposed in public surface area).

**Comment by keegan-caruso** [comment]
Mostly a duplicate of  #17

**Comment by jhendrixMSFT** [comment]
Closing as dupe.
