### ISSUE TITLE
[Bug] APIs that perform I/O must take a `context.Context` as their first parameter

### ISSUE THREAD

**Issue by jhendrixMSFT** [AzureAD/microsoft-authentication-library-for-go#56]
E.g. `ConfidentialClientApplication.AcquireTokenByClientCredential()` should have a first param `ctx context.Context`.

This indicates to the caller that the API performs an I/O request and allows the caller to control the lifetime of the request.

**Comment by devigned** [comment]
Passing in a context a `ctx` is a must have. My team would hesitate to take a dependency on a rpc library that didn't allow for request cancellation.

**Comment by jhendrixMSFT** [comment]
This has been fixed in the `dev` branch.

**Comment by jhendrixMSFT** [comment]
Found a few more APIs that need a context.

**Comment by jhendrixMSFT** [comment]
Should be fully fixed now.
