### ISSUE TITLE
[Feature Request] Shared token cache across platforms (encrypted and persisted to disc for Desktop applications)

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-authentication-library-for-go#58]
This is for for Desktop applications persisting to disk and doing so encrypted

- Extensions library
- shared token cache w/other dev tools

**Comment by chlowell** [comment]
This is implemented in [github.com/AzureAD/microsoft-authentication-extensions-for-go/cache](https://pkg.go.dev/github.com/AzureAD/microsoft-authentication-extensions-for-go/cache)
