### ISSUE TITLE
[Cleanup] Provision for optional arguments

### ISSUE THREAD

**Issue by jhendrixMSFT** [AzureAD/microsoft-authentication-library-for-go#69]
Establish a pattern for handling optional arguments.  This should be established up front as the design might impact public surface area.

The idea is to provide a mechanism to avoid breaking changes in the event that we want to add a new, optional parameter to an API.

1. options struct to hold optional params
2. variadic configuration pattern
3. add new APIs with a suffix, e.g. `WithFoo()` 

Option 1 and 2 are detailed [here](https://blog.golang.org/module-compatibility).  Option 3 should be avoided.

**Comment by element-of-surprise** [comment]
Looks like we've added a hybrid of all these?

```go
type Options struct {
  // User 
  User string
}

type Option func(o *Options)

type WithUser(user string) Option {
  return func(o *Options) {
    o.User = user
  }
}

func New(arg1 string, options ...Option) *MyType {
  opts := Options{
    User: "nobody",
  }

  for _, o := range options {
    o(&opts)
  }
  ...
}
```

# 1 to have a list of all options in a single place for documentation
#2 to have a nicer call and support a better defaults options pattern
#3 was suggested.  "With" is not something I have a lot of feeling about.

Is this method sufficient?  Can we close or need to discuss on this more?

**Comment by jhendrixMSFT** [comment]
This is a big improvement over the original implementation.
