### ISSUE TITLE
[Bug] Include openid claim by default

### ISSUE THREAD

**Issue by jhendrixMSFT** [AzureAD/microsoft-authentication-library-for-go#72]
Per discussion in https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/68#discussion_r516579020

Align with the other MSAL implementations regarding default claims.

**Comment by jmprieur** [comment]
We really want to add openid, profile and offline_access.

**Comment by jhendrixMSFT** [comment]
I dug into this some more, turns out we already add those three to the list of scopes provided by the caller.

https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/msal/default_web_request_manager.go#L206

I think this bug can be closed, do you agree?

**Comment by jmprieur** [comment]
Yes, I agree. Thanks for the heads-up, @jhendrixMSFT
