### ISSUE TITLE
[Cleanup] Return single account for ConfidentialClientApplication

### ISSUE THREAD

**Issue by jhendrixMSFT** [AzureAD/microsoft-authentication-library-for-go#73]
Per discussion in https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/68#discussion_r516576827

The `Accounts()` method returns a slice of accounts in a confidential client app however there will always only be one account.

There is no singular `Account()` method at present.

**Comment by jmprieur** [comment]
@jhendrixMSFT normally `Accounts()` should not return any account if the cache is well implemented, as there should be one cache per account, and I don't think that `Accounts()` would know which account/Msal account ID to use? would it?

**Comment by abhidnya13** [comment]
Resolved in #184. We only have `Account(homeAccountID)` in confidential client apps which returns a single account associated with the specified `homeAccoundID`
