### ISSUE TITLE
[Fundamentals] Rename master branch to main

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-go#85]
**Main branch**
_An inclusive new default_
New repos created within Microsoft orgs now have the default branch name of 'main'.

Teams are encouraged to rename their default branches if they are still using the 'master' branch name. This is an important, but not urgent, change.

**See more:**
https://repos.opensource.microsoft.com/

**Comment by abhidnya13** [comment]
Closed in the latest release.
