### ISSUE TITLE
[Feature Request] Create auxiliary token

### ISSUE THREAD

**Issue by PakDLiu** [AzureAD/microsoft-authentication-library-for-go#91]
**Is your feature request related to a problem? Please describe.**
I am trying to do VNet injection according to this [document](https://microsoft.sharepoint.com/:w:/r/teams/vnet/_layouts/15/guestaccess.aspx?e=WO8L0R&share=EQUeBXKSRrtHvbhR3t_ih5QBCzOCGaf_9eA5aBfY5R6IOQ).
To do VNet injection with a VM, the networking resources are creating in the customer's subscription and the VM is created in our service subscription, using those networking resources. To do create the VM in that manner, an auxiliary token is required for authentication.

**Describe the solution you'd like**
I need a way to be able to create a mulit-tenant service principal token like in the [old adal library](https://github.com/Azure/go-autorest/blob/e85e33a04d242eb0eba5408e4dadf8783047b62f/autorest/adal/token.go#L1162), except created from a certificate rather than client ID and secret.

**Describe alternatives you've considered**
I've looked into the old adal library and only found a way to [create the mulit-tenant service principal token from client ID and secret](https://github.com/Azure/go-autorest/blob/e85e33a04d242eb0eba5408e4dadf8783047b62f/autorest/adal/token.go#L1162), however, I need to create the token from a certificate, much like this [old method (not multi-tenant)](https://github.com/Azure/go-autorest/blob/e85e33a04d242eb0eba5408e4dadf8783047b62f/autorest/adal/token.go#L563).

**Comment by sangonzal** [comment]
Hi @PakDLiu, as discussed via email, this should be feature request for go-autorest and not MSAL. Linking to open issue in go-autorest: https://github.com/Azure/go-autorest/issues/509
