### ISSUE TITLE
[Bug] Update DeleteAccounts

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-go#93]
- Use RemoveAccount to be consistent with other libraries
- Update paramaters to get rid of envAliases[]. User should not have to pass this in. Might also consider using an Account object instead of homeAccountId. 
- RemoveAccounts should remove the account and any associated accessTokens, refreshTokens, and IdTokens. In it's current implementation, I think it's only removing accounts. 
- Expose RemoveAccount on clientApplication.

**Comment by abhidnya13** [comment]
Resolved in #215
