### ISSUE TITLE
[Bug] Panic from CreateAuthCodeURL if passed an invalid Authority URL

### ISSUE THREAD

**Issue by harikb** [AzureAD/microsoft-authentication-library-for-go#95]
MSAL repo HEAD as of today (where do I find the version number?)

**Where is the issue?**
* Public client
    * [ X] Authorization code flow 

**Is this a new or an existing app?**

**What version of Go are you using (`go version`)?**

<pre>
go version go1.15.6 darwin/amd64
</pre>

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/harikb/Library/Caches/go-build"
GOENV="/Users/harikb/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/harikb/dev/code/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/harikb/dev/code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/harikb/dev/code/src/github.com/AzureAD/microsoft-authentication-library-for-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bw/tghp9_kj1wb6pkx2mc_18cd00000gn/T/go-build403398122=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Repro**
If you pass in "https://some-incorrect-url.microsoftonline.com/<valid-tenantid>" for AuthorityURL, you get a panic. Btw, "https://login.microsoftonline.com/[invalid-tenant-id]/" is properly checked for.

**Expected behavior**
Should return an error, instead of panic. 

**Actual behavior**
panics with this trace
<pre>
INFO[0003] Resolving authority endpoints. No cached value.  Performing lookup.

 panic: runtime error: invalid memory address or nil pointer dereference

 -> github.com/AzureAD/microsoft-authentication-library-for-go/internal/requests.(*AadInstanceDiscovery).doInstanceDiscoveryAndCache
 ->   /Users/harikb/dev/code/pkg/mod/github.com/!azure!a!d/microsoft-authentication-library-for-go@v0.0.0-20201202214456-df1404537070/internal/requests/aad_instance_discovery.go:23

    github.com/AzureAD/microsoft-authentication-library-for-go/internal/requests.(*AadInstanceDiscovery).GetMetadataEntry
      /Users/harikb/dev/code/pkg/mod/github.com/!azure!a!d/microsoft-authentication-library-for-go@v0.0.0-20201202214456-df1404537070/internal/requests/aad_instance_discovery.go:44
    github.com/AzureAD/microsoft-authentication-library-for-go/internal/requests.(*aadOpenIDConfigurationEndpointManager).getOpenIDConfigurationEndpoint
      /Users/harikb/dev/code/pkg/mod/github.com/!azure!a!d/microsoft-authentication-library-for-go@v0.0.0-20201202214456-df1404537070/internal/requests/oidc_endpoint_manager.go:46
    github.com/AzureAD/microsoft-authentication-library-for-go/internal/requests.(*AuthorityEndpointResolutionManager).ResolveEndpoints
      /Users/harikb/dev/code/pkg/mod/github.com/!azure!a!d/microsoft-authentication-library-for-go@v0.0.0-20201202214456-df1404537070/internal/requests/authority_endpoint_resolution_manager.go:98
    github.com/AzureAD/microsoft-authentication-library-for-go/msal.AuthorizationCodeURLParameters.createURL
      /Users/harikb/dev/code/pkg/mod/github.com/!azure!a!d/microsoft-authentication-library-for-go@v0.0.0-20201202214456-df1404537070/msal/authorization_code_url_parameters.go:46
    github.com/AzureAD/microsoft-authentication-library-for-go/msal.(*clientApplication).createAuthCodeURL
      /Users/harikb/dev/code/pkg/mod/github.com/!azure!a!d/microsoft-authentication-library-for-go@v0.0.0-20201202214456-df1404537070/msal/client_application.go:43
    github.com/AzureAD/microsoft-authentication-library-for-go/msal.(*PublicClientApplication).CreateAuthCodeURL
      /Users/harikb/dev/code/pkg/mod/github.com/!azure!a!d/microsoft-authentication-library-for-go@v0.0.0-20201202214456-df1404537070/msal/public_client_application.go:62
</pre>

**Comment by element-of-surprise** [comment]
All of this code is mostly gone.  It is unlikely that this problem has survived. We are now in the process of adding integration tests for all flows. Let me know if you find any problems related to the new version of this package.
